[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
rtp_treasury = "8rt6yiBnRTyHy8F69jUd7exWwwShUs4Eokeq41auo2RB"

[programs.localnet]
rtp_treasury = "8rt6yiBnRTyHy8F69jUd7exWwwShUs4Eokeq41auo2RB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
